# Generated by Django 5.1.5 on 2025-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
