# Generated by Django 5.1.5 on 2025-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
