# Generated by Django 5.1.5 on 2025-05-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_studentfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFee',
        ),
    ]
