# Generated by Django 5.1.5 on 2025-05-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_subject_subjectdiary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subjectdiary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectdiary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='school.subject'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='school_subj_name_880daa_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectdiary',
            index=models.Index(fields=['created_at'], name='school_subj_created_36d37b_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectdiary',
            index=models.Index(fields=['subject'], name='school_subj_subject_1a66f3_idx'),
        ),
    ]
