# Generated by Django 5.1.5 on 2025-05-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_diary_delete_teacherdiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
    ]
