# Generated by Django 5.1.5 on 2025-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_diary_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
