# Generated by Django 5.1.5 on 2025-05-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_diary_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
