# Generated by Django 5.1.5 on 2025-05-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_diary'),
    ]

    operations = [
    ]
