# Generated by Django 5.1.5 on 2025-05-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20250504_0436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
