# Generated by Django 5.1.5 on 2025-05-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_subject_diary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
