# Generated by Django 5.1.5 on 2025-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
