# Generated by Django 5.1.5 on 2025-05-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_teacherreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherReview',
        ),
    ]
